<?php
/*"******************************************************************************************************
*   (c) 2004-2006 by MulchProductions, www.mulchprod.de                                                 *
*   (c) 2007-2015 by Kajona, www.kajona.de                                                              *
*       Published under the GNU LGPL v2.1, see /system/licence_lgpl.txt                                 *
*-------------------------------------------------------------------------------------------------------*
*	$Id$					    *
********************************************************************************************************/
//Edited with Kajona Language Editor GUI, see www.kajona.de and www.mulchprod.de for more information
//Kajona Language Editor Core Build 398


//editable entries
$lang["action_config"]                   = "Settings";
$lang["action_edit"]                     = "Detailed view";
$lang["action_show_all"]                 = "Show all messages";
$lang["batchaction_read"]                = "Mark as read";
$lang["batchaction_unread"]              = "Mark as unread";
$lang["delete_question"]                 = "Do you really want to delete the message &quot;<b>%%element_name%%</b>&quot;?";
$lang["message_body"]                    = "Message";
$lang["message_date"]                    = "Date";
$lang["message_link"]                    = "Detailed view";
$lang["message_not_existing"]            = "Error loading the requested message, maybe it was deleted in the meantime.";
$lang["message_notification_subject"]    = "New message received";
$lang["message_prolog"]                  = "You got a new message. To open the message, use the link below. A copy of the message is attached.";
$lang["message_reference"]               = "References to";
$lang["message_reply"]                   = "Reply";
$lang["message_sender"]                  = "Sender";
$lang["message_sent_success"]            = "The message was sent successfully.";
$lang["message_subject"]                 = "Subject";
$lang["message_to"]                      = "To";
$lang["message_type"]                    = "Typ";
$lang["messageprovider_packageupdate_name"] = "Update-Messages";
$lang["messaging_notification_body"]     = "You received a new message. Click on this notification to open the list of messages.";
$lang["messaging_notification_title"]    = "New Messages";
$lang["modul_titel"]                     = "Messages";
$lang["provider_bymail"]                 = "Email notifications";
$lang["provider_enabled"]                = "Enabled";
$lang["provider_title"]                  = "Message-Type";
$lang["quickhelp_config"]                = "The menu item 'Settings' of messaging functions allows to enable or disable the sending of messages in case of certain events (e.g. tasks with upcoming due dates). Once the feature is enabled, the relevant messages are displayed in the corresponding list of messages. Moreover, it is possible to additionally send an e-mail notification to each registered e-mail address. This has to be enabled / disabled for each message type.";
$lang["quickhelp_list"]                  = "The screen ‘Messages’ displays all user specific messages, which are automatically generated by the system (e.g. information on due dates of individual tasks) and which are relevant for the respective user. The list contains the unread messages, followed by the read messages (in descending order).";
$lang["delete_all_read_question"] = "You you really want to delete all read messages?";
$lang["delete_all_question"] = "Do you really want to delete all messages?";
$lang["action_delete_all_read"] = "Delete read messages";
$lang["action_delete_all"] = "Delete all messages";
$lang["action_set_all_read"] = "Mark all as read";