<?php
/*"******************************************************************************************************
*   (c) 2004-2006 by MulchProductions, www.mulchprod.de                                                 *
*   (c) 2007-2015 by Kajona, www.kajona.de                                                              *
*       Published under the GNU LGPL v2.1, see /system/licence_lgpl.txt                                 *
*-------------------------------------------------------------------------------------------------------*
*	$Id$					    *
********************************************************************************************************/
//Edited with Kajona Language Editor GUI, see www.kajona.de and www.mulchprod.de for more information
//Kajona Language Editor Core Build 398


//editable entries
$lang["action_add_widget_to_dashboard"]  = "Add widget";
$lang["action_calendar"]                 = "Calendar";
$lang["action_sitemap"]                  = "Sitemap";
$lang["action_todo"]                     = "Open tasks";
$lang["addWidgetNextStep"]               = "Next";
$lang["calendar_next"]                   = "next month &gt;&gt;";
$lang["calendar_prev"]                   = "&lt;&lt; previous month";
$lang["calendar_weekday"]                = "Monday,Tuesday,Wednesday,Thursday,Friday,Saturday,Sunday";
$lang["column"]                          = "Column";
$lang["column1"]                         = "Column 1";
$lang["column2"]                         = "Column 2";
$lang["column3"]                         = "Column 3";
$lang["deleteWidgetSuccess"]             = "The widget {0} was deleted successfully";
$lang["editWidget"]                      = "Edit widget";
$lang["errorSavingWidget"]               = "Error saving the widget";
$lang["globalSearchPlaceholder"]         = "Searchquery";
$lang["modul_titel"]                     = "Overview";
$lang["quickhelp_add_widget_to_dashboard"] = "To add a widget to the dashboard choose the widget to add and the column to pin it to. In the next step, the widget itself can be configured.";
$lang["quickhelp_calendar"]              = "The screen ‘Calendar’ supports the visualization of due dates and events in calendar format. Thus, for example, tasks are shown as tasks on the respective due dates. Further information like corresponding facts and relevant details can be generated by clicking on the respective calendar events.";
$lang["quickhelp_list"]                  = "The dashboard is the place to pin every kind of widget. A widget is a small program presenting a piece of information. The widgets can be sorted, edited and deleted right on the dashboard. To add new widgets, use the action \"add widget\". ";
$lang["setDashboardPosition"]            = "New position saved successful";
$lang["widget"]                          = "Widget";
$lang["widgetDeleteQuestion"]            = "Do you really want to remove the widget &quot;<b>%%element_name%%</b>&quot;?";
$lang["todo_name"]                       = "Open tasks";
$lang["todo_no_open_tasks"]              = "No open tasks available";
$lang["todo_overall_tasks"]              = "Overall";
$lang["filter_category"]                 = "Category";
$lang["filter_search"]                   = "Search";
$lang["filter_date"]                     = "Resolution date";
$lang["filter_all_categories"]           = "All categories";
$lang["todo_task_col_object"]            = "Object";
$lang["todo_task_col_category"]          = "Category";
$lang["todo_task_col_date"]              = "Resolution date";
