# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "Kajona Development"
  config.vm.provider "virtualbox" do |v|
    v.name = "Development"
    v.gui = true
    v.cpus = 2
    v.memory = 2048
  end

  config.vm.provider "parallels" do |v|
    v.name = "Kajona Development"
    v.update_guest_tools = true
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision :shell, path: "Bootstrap.sh"
  
end
