<?php
/*"******************************************************************************************************
*   (c) 2004-2006 by MulchProductions, www.mulchprod.de                                                 *
*   (c) 2007-2016 by Kajona, www.kajona.de                                                              *
*       Published under the GNU LGPL v2.1, see /system/licence_lgpl.txt                                 *
*-------------------------------------------------------------------------------------------------------*
*	$Id$					    *
********************************************************************************************************/
//Edited with Kajona Language Editor GUI, see www.kajona.de and www.mulchprod.de for more information
//Kajona Language Editor Core Build 385

//editable entries
$lang["delete_question"]                 = "Do you really want to delete the navigation &quot;<b>%%element_name%%</b>&quot; with all items?";
$lang["error_folder_and_page"]           = "Only a page or a folder can be selected, not both.";
$lang["liste_leer"]                      = "No navigations available";
$lang["modul_anlegenpunkt"]              = "Create navigation item";
$lang["modul_titel"]                     = "Navigations";
$lang["action_new_navi"]               = "Create navigation";
$lang["navigation_anzeigen"]             = "Show navigation items";
$lang["navigation_erf_loeschen"]         = "Navigation was deleted succesfully";
$lang["navigation_erfolg"]               = "Navigation was created succesfully";
$lang["navigation_folder_i"]             = "Folder";
$lang["navigation_page_e"]               = "External link / file";
$lang["navigation_page_i"]               = "Page";
$lang["navigation_parent"]               = "Parent node";
$lang["navigation_point_accept"]         = "Accept navigation item";
$lang["navigation_show_disabled"]        = "Navigation items can\'t be shown since they are generated automatically.";
$lang["navigation_tagetblank"]           = "_blank (in a new browser window)";
$lang["navigation_tagetself"]            = "_self (in the same browser window)";
$lang["navigation_target"]               = "Target";
$lang["navigationp_anzeigen"]            = "Show navigation items";
$lang["quickhelp_delete_navi"]           = "By executing the 'delete' function the selected navigation tree or navigation tree item and all sub items will be deleted. This step is irreversible.";
$lang["quickhelp_edit_navi"]             = "You can edit the properties of the navigation tree here.";
$lang["quickhelp_edit_navi_point"]       = "By creating and editing a navigation item you can change its properties. The properties include the item name and the corresponding link. For external websites you can use the field 'External link'. If you want to have an image to be shown instead of the item name, you can use the field 'Image'. You can choose the target of the link with the corresponding drop down.";
$lang["quickhelp_list"]                  = "The list shows all existing navigation trees und their items. The sort sequence of navigation items in the same level can be changed by clicking on the arrows.";
$lang["quickhelp_new_navi"]              = "To create a new navigation tree you just have to assign a titel to it. The name can be changed by using the 'edit' function later.";
$lang["quickhelp_new_navi_point"]        = "By creating and editing a navigation item you can change its properties. The properties include the item name and the corresponding link. For external websites you can use the field 'External link'. If you want to have an image to be shown instead of the item name, you can use the field 'Image'. You can choose the target of the link with the corresponding drop down.";
$lang["required_navigation_name"]        = "Name";
$lang["systemtask_navigationcheck_autogenerated"] = "navigation is autogenerated, skipping";
$lang["systemtask_navigationcheck_invalidBoth"] = "Error, internal and external target set!";
$lang["systemtask_navigationcheck_invalidEmpty"] = "Error, target not set!";
$lang["systemtask_navigationcheck_invalidInternal"] = "Error, internal page doesn't exists! (Target";
$lang["systemtask_navigationcheck_name"] = "Validate navigationpoints";
$lang["systemtask_navigationcheck_treescan"] = "Investigate navigation";
$lang["systemtask_navigationcheck_valid"] = "valid (Target";
