<?php
/*"******************************************************************************************************
*   (c) 2004-2006 by MulchProductions, www.mulchprod.de                                                 *
*   (c) 2007-2016 by Kajona, www.kajona.de                                                              *
*       Published under the GNU LGPL v2.1, see /system/licence_lgpl.txt                                 *
*-------------------------------------------------------------------------------------------------------*
*	$Id$					    *
********************************************************************************************************/
//Edited with Kajona Language Editor GUI, see www.kajona.de and www.mulchprod.de for more information
//Kajona Language Editor Core Build 385

//editable entries
$lang["delete_question"]                 = "Möchten Sie die Navigation &quot;<b>%%element_name%%</b>&quot; mit allen Unterpunkten wirklich löschen?";
$lang["error_folder_and_page"]           = "Es kann entweder eine Seite oder ein Ordner ausgewählt werden, nicht beides.";
$lang["liste_leer"]                      = "Keine Navigation angelegt";
$lang["modul_anlegenpunkt"]              = "Neuer Unterpunkt";
$lang["modul_titel"]                     = "Navigationen";
$lang["action_new_navi"]               = "Neue Navigation";
$lang["navigation_anzeigen"]             = "Unterpunkte anzeigen";
$lang["navigation_erf_loeschen"]         = "Navigation erfolgreich gelöscht";
$lang["navigation_erfolg"]               = "Navigation erfolgreich angelegt";
$lang["navigation_folder_i"]             = "Ordner";
$lang["navigation_page_e"]               = "Externer Verweis / Datei";
$lang["navigation_page_i"]               = "Interne Seite";
$lang["navigation_parent"]               = "Übergeordneter Knoten";
$lang["navigation_point_accept"]         = "Navigationspunkt übernehmen";
$lang["navigation_show_disabled"]        = "Navigationspunkte können nicht angezeigt werden, da diese automatisch generiert werden.";
$lang["navigation_tagetblank"]           = "_blank (Neues Browserfenster)";
$lang["navigation_tagetself"]            = "_self (Selbes Browserfenster)";
$lang["navigation_target"]               = "Ziel";
$lang["navigationp_anzeigen"]            = "Unterpunkte anzeigen";
$lang["quickhelp_delete_navi"]           = "Mit dieser Aktion wird eine Navigation oder ein Navigationspunkt mit allen Unterpunkten aus dem System gelöscht. Dieser Schritt kann nicht rückgängig gemacht werden.";
$lang["quickhelp_edit_navi"]             = "Für eine neue Navigation muss lediglich der Titel des Navigationsbaumes vergeben werden. Über die Aktion 'bearbeiten' kann dieser später wieder verändert werden.";
$lang["quickhelp_edit_navi_point"]       = "Beim Anlegen oder Bearbeiten eines Navigationspunktes können dessen Eigenschaften verändert werden. Hierzu gehören der Name der Punktes, sowie die Seite, auf welche der Punkt zeigen soll. Für externe Seiten kann das Feld 'externer Verweis' verwendet werden. Soll statt des Namens ein Bild geladen werden, so kann dies unter 'Bild' angegeben werden. Das Ziel gibt das spätere Link-Target an.";
$lang["quickhelp_list"]                  = "Alle im System angelegten Navigationsbäume und dessen Unterpunkte werden in dieser Liste angezeigt.Die Sortierung der Navigationspunkte einer Ebene zueinander kann über Anklicken der Pfeil-Grafiken verändert werden.";
$lang["quickhelp_new_navi"]              = "Für eine neue Navigation muss lediglich der Titel des Navigationsbaumes vergeben werden. Über die Aktion 'bearbeiten' kann dieser später wieder verändert werden.";
$lang["quickhelp_new_navi_point"]        = "Beim Anlegen oder Bearbeiten eines Navigationspunktes können dessen Eigenschaften verändert werden. Hierzu gehören der Name der Punktes, sowie die Seite, auf welche der Punkt zeigen soll. Für externe Seiten kann das Feld 'externer Verweis' verwendet werden. Soll statt des Namens ein Bild geladen werden, so kann dies unter 'Bild' angegeben werden. Das Ziel gibt das spätere Link-Target an.";
$lang["required_navigation_name"]        = "Name";
$lang["systemtask_navigationcheck_autogenerated"] = "Navigation wird automatisch generiert, wird übersprungen";
$lang["systemtask_navigationcheck_invalidBoth"] = "Fehler, internes und externes Ziel gesetzt!";
$lang["systemtask_navigationcheck_invalidEmpty"] = "Fehler, kein Ziel gesetzt!";
$lang["systemtask_navigationcheck_invalidInternal"] = "Fehler, interne Seite existiert nicht! (Ziel";
$lang["systemtask_navigationcheck_name"] = "Navigationspunkte validieren";
$lang["systemtask_navigationcheck_treescan"] = "Untersuche Navigation";
$lang["systemtask_navigationcheck_valid"] = "gültig (Ziel";
